// Code generated by protoc-gen-go.
// source: auth.proto
// DO NOT EDIT!

/*
Package slickqa is a generated protocol buffer package.

It is generated from these files:
	slickqa.proto

It has these top-level messages:
	IsAuthorizedRequest
	IsAuthorizedResponse
*/
package slickqa

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type IsAuthorizedRequest struct {
	Permission string `protobuf:"bytes,1,opt,name=permission" json:"permission,omitempty"`
}

func (m *IsAuthorizedRequest) Reset()                    { *m = IsAuthorizedRequest{} }
func (m *IsAuthorizedRequest) String() string            { return proto.CompactTextString(m) }
func (*IsAuthorizedRequest) ProtoMessage()               {}
func (*IsAuthorizedRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *IsAuthorizedRequest) GetPermission() string {
	if m != nil {
		return m.Permission
	}
	return ""
}

type IsAuthorizedResponse struct {
	Allowed bool `protobuf:"varint,1,opt,name=allowed" json:"allowed,omitempty"`
}

func (m *IsAuthorizedResponse) Reset()                    { *m = IsAuthorizedResponse{} }
func (m *IsAuthorizedResponse) String() string            { return proto.CompactTextString(m) }
func (*IsAuthorizedResponse) ProtoMessage()               {}
func (*IsAuthorizedResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *IsAuthorizedResponse) GetAllowed() bool {
	if m != nil {
		return m.Allowed
	}
	return false
}

func init() {
	proto.RegisterType((*IsAuthorizedRequest)(nil), "com.slickqa.IsAuthorizedRequest")
	proto.RegisterType((*IsAuthorizedResponse)(nil), "com.slickqa.IsAuthorizedResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Auth service

type AuthClient interface {
	IsAuthorized(ctx context.Context, in *IsAuthorizedRequest, opts ...grpc.CallOption) (*IsAuthorizedResponse, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) IsAuthorized(ctx context.Context, in *IsAuthorizedRequest, opts ...grpc.CallOption) (*IsAuthorizedResponse, error) {
	out := new(IsAuthorizedResponse)
	err := grpc.Invoke(ctx, "/com.slickqa.Auth/IsAuthorized", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Auth service

type AuthServer interface {
	IsAuthorized(context.Context, *IsAuthorizedRequest) (*IsAuthorizedResponse, error)
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_IsAuthorized_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsAuthorizedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).IsAuthorized(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.slickqa.Auth/IsAuthorized",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).IsAuthorized(ctx, req.(*IsAuthorizedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.slickqa.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsAuthorized",
			Handler:    _Auth_IsAuthorized_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "slickqa.proto",
}

func init() { proto.RegisterFile("slickqa.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 233 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x2c, 0x2d, 0xc9,
	0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4e, 0xce, 0xcf, 0xd5, 0x2b, 0xce, 0xc9, 0x4c,
	0xce, 0x2e, 0x4c, 0x94, 0x92, 0x49, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x4f, 0x2c, 0xc8, 0xd4,
	0x4f, 0xcc, 0xcb, 0xcb, 0x2f, 0x49, 0x2c, 0xc9, 0xcc, 0xcf, 0x2b, 0x86, 0x28, 0x55, 0x32, 0xe5,
	0x12, 0xf6, 0x2c, 0x76, 0x2c, 0x2d, 0xc9, 0xc8, 0x2f, 0xca, 0xac, 0x4a, 0x4d, 0x09, 0x4a, 0x2d,
	0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x92, 0xe3, 0xe2, 0x2a, 0x48, 0x2d, 0xca, 0xcd, 0x2c, 0x2e, 0xce,
	0xcc, 0xcf, 0x93, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x42, 0x12, 0x51, 0x32, 0xe0, 0x12, 0x41,
	0xd5, 0x56, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x2a, 0x24, 0xc1, 0xc5, 0x9e, 0x98, 0x93, 0x93, 0x5f,
	0x9e, 0x9a, 0x02, 0xd6, 0xc4, 0x11, 0x04, 0xe3, 0x1a, 0xb5, 0x31, 0x72, 0xb1, 0x80, 0x34, 0x08,
	0xd5, 0x71, 0xf1, 0x20, 0x6b, 0x15, 0x52, 0xd0, 0x43, 0x72, 0xad, 0x1e, 0x16, 0xc7, 0x48, 0x29,
	0xe2, 0x51, 0x01, 0xb1, 0x57, 0x49, 0xb3, 0xe9, 0xf2, 0x93, 0xc9, 0x4c, 0xca, 0x42, 0x8a, 0x60,
	0x6f, 0x96, 0x19, 0xea, 0x67, 0x22, 0xa9, 0xd2, 0xaf, 0x46, 0xb8, 0xbc, 0xd6, 0xc9, 0x85, 0x4b,
	0x1a, 0xd9, 0xb8, 0xe4, 0x9c, 0xcc, 0xd4, 0xbc, 0x12, 0x48, 0x68, 0x24, 0x95, 0xa6, 0x45, 0xb1,
	0x43, 0x25, 0x56, 0x31, 0xe1, 0x53, 0x96, 0xc4, 0x06, 0x66, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x7d, 0xd4, 0x30, 0x3c, 0x77, 0x01, 0x00, 0x00,
}
